version: '3'
services:
  account:
    build: ./account  # Specify the path to the account microservice Dockerfile
    # ports:
    #   - 8000:8000  # Map the container's port to the host machine's port

  shop:
    build: ./shop  # Specify the path to the shop microservice Dockerfile
    # ports:
    #   - 8001:8001  # Map the container's port to the host machine's port

  order:
    build: ./order
    # ports:
    #   - 8002:8002


  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account
      - shop
      - order


  haproxy:
    image: haproxy:latest
    ports:
      - 8080:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - nginx
